# Generated by Django 3.0.5 on 2023-02-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sold', models.IntegerField()),
                ('temp', models.FloatField()),
                ('weekday_1', models.BooleanField()),
                ('weekday_2', models.BooleanField()),
                ('weekday_3', models.BooleanField()),
                ('weekday_4', models.BooleanField()),
                ('weekday_5', models.BooleanField()),
                ('weekday_6', models.BooleanField()),
                ('weekday_7', models.BooleanField()),
                ('weather_status_Klart', models.BooleanField()),
                ('weather_status_Moln', models.BooleanField()),
                ('weather_status_Regn', models.BooleanField()),
                ('weather_status_Sno', models.BooleanField()),
            ],
        ),
    ]
