# Generated by Django 3.0.5 on 2023-02-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
