# Generated by Django 3.0.5 on 2023-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20230220_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='actual_sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('sold', models.IntegerField()),
            ],
            options={
                'db_table': 'actual_sales',
            },
        ),
    ]
