# Generated by Django 3.0.5 on 2023-02-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_actual_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual_sold',
            name='id',
        ),
        migrations.AlterField(
            model_name='actual_sold',
            name='date',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
