# Generated by Django 3.0.5 on 2023-02-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20230220_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='id',
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
