# Generated by Django 3.0.5 on 2023-02-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_delete_actual_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='actual_sold',
            fields=[
                ('date', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sold', models.IntegerField()),
            ],
            options={
                'db_table': 'actual_sales',
            },
        ),
    ]
